# Generated by Django 6.1.1 on 2026-09-12 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('prescribed_date', models.DateField(default=django.utils.timezone.now)),
                ('instructions', models.TextField(blank=True, help_text='General advice for the patient')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.doctor')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-prescribed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('dosage', models.CharField(help_text='e.g. 500 mg', max_length=60)),
                ('frequency', models.CharField(help_text='e.g. 1+0+1 (twice a day)', max_length=60)),
                ('duration', models.CharField(help_text='e.g. 7 days', max_length=60)),
                ('route', models.CharField(choices=[('Oral', 'Oral'), ('Topical', 'Topical'), ('Injection', 'Injection'), ('Inhalation', 'Inhalation'), ('Drops', 'Drops')], default='Oral', max_length=30)),
                ('special_instruction', models.CharField(blank=True, max_length=200)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
